version: "3.9"
services:
  db:
    image: postgres:14.5-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=cienciastop_db
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    image: amazoncorretto:17-alpine
    working_dir: /home/app
    ports:
      - 10000:10000
    command: ./mvnw spring-boot:run
    depends_on:
      - db
    volumes:
      - .:/home/app
      - mvn_data:/root/.m2
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/cienciastop_db

#  pg:
#    image: dpage/pgadmin4
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=dev@cienciastop.com
#      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
#    ports:
#      - "80:80"

volumes:
  mvn_data:
  db_data:
